#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#define vrmlScene 1
#define statements 2
#define statement 3
#define nodeStatement 4
#define empty 5
#define node 6
#define nodeBody 7
#define scriptBody 8
#define scriptBodyElement 9
#define nodeBodyElement 10
#define nodeNameId 11
#define nodeTypeId 12
#define fieldId 13
#define eventInId 14
#define eventOutId 15
#define Id 16
#define IdFirstChar 17
#define IdRestChars 18
#define fieldType 19
#define fieldValue 20
#define sfboolValue 21 
#define sfcolorValue 22
#define sffloatValue 23
#define float 24
#define sfimageValue 25 
#define sfint32Value 26
#define int32 27
#define sfnodeValue 28
#define sfrotationValue 29
#define sfstringValue 30
#define string 31
#define sftimeValue 32
#define double 33
#define mftimeValue 34
#define sftimeValues 35
#define sfvec2fValue 36
#define sfvec3fValue 37
#define mfcolorValue 38
#define sfcolorValues 39
#define mffloatValue 40
#define sffloatValues 41
#define mfint32Value 42
#define sfint32Values 43
#define mfnodeValue 44
#define nodeStatements 45
#define mfrotationValue 46
#define sfrotationValues 47
#define mfstringValue 48
#define sfstringValues 49
#define mfvec2fValue 50
#define sfvec2fValues 51
#define mfvec3fValue 52
#define sfvec3fValues 53
#endif